-- MySQL Script generated by MySQL Workbench
-- mar 22 oct 2019 09:59:39 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`audioria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`audioria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`audioria` (
  `idaudioria` INT NOT NULL AUTO_INCREMENT,
  `audi_nombre` VARCHAR(45) NULL,
  `audi_fecha` DATE NULL,
  PRIMARY KEY (`idaudioria`),
  UNIQUE INDEX `idaudioria_UNIQUE` (`idaudioria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sistema_operativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sistema_operativo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sistema_operativo` (
  `idsistema_operativo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `arquitectura` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `directorio` VARCHAR(45) NULL,
  PRIMARY KEY (`idsistema_operativo`),
  UNIQUE INDEX `idsistema_operativo_UNIQUE` (`idsistema_operativo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cpu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cpu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cpu` (
  `idcpu` INT NOT NULL AUTO_INCREMENT,
  `vendedor` VARCHAR(100) NULL,
  `modelo` VARCHAR(100) NULL,
  `mhz` VARCHAR(100) NULL,
  `tam_cache` VARCHAR(100) NULL,
  `cpufisica` VARCHAR(100) NULL,
  `nucleoscpu` VARCHAR(100) NULL,
  PRIMARY KEY (`idcpu`),
  UNIQUE INDEX `idcpu_UNIQUE` (`idcpu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`red`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`red` ;

CREATE TABLE IF NOT EXISTS `mydb`.`red` (
  `idred` INT NOT NULL AUTO_INCREMENT,
  `ip_primaria` VARCHAR(45) NULL,
  `mac_primaria` VARCHAR(100) NULL,
  `host` VARCHAR(45) NULL,
  PRIMARY KEY (`idred`),
  UNIQUE INDEX `idred_UNIQUE` (`idred` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`disco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`disco` (
  `iddisco` INT NOT NULL AUTO_INCREMENT,
  `espaciototal` VARCHAR(45) NULL,
  `espaciodisponible` VARCHAR(45) NULL,
  `espaciousado` VARCHAR(45) NULL,
  `unidades` VARCHAR(45) NULL,
  PRIMARY KEY (`iddisco`),
  UNIQUE INDEX `iddisco_UNIQUE` (`iddisco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audi_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`audi_equipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`audi_equipo` (
  `idaudi_equipo` INT NOT NULL AUTO_INCREMENT,
  `num_equipo` INT NOT NULL,
  `idauditoria` INT NOT NULL,
  `sistema_operativo` INT NOT NULL,
  `cpu` INT NOT NULL,
  `red_idred` INT NOT NULL,
  `disco_iddisco` INT NOT NULL,
  PRIMARY KEY (`idaudi_equipo`),
  UNIQUE INDEX `idaudi_equipo_UNIQUE` (`idaudi_equipo` ASC),
  INDEX `fk_audi_equipo_audioria_idx` (`idauditoria` ASC),
  INDEX `fk_audi_equipo_sistema_operativo1_idx` (`sistema_operativo` ASC),
  INDEX `fk_audi_equipo_cpu1_idx` (`cpu` ASC),
  UNIQUE INDEX `num_equipo_UNIQUE` (`num_equipo` ASC),
  INDEX `fk_audi_equipo_red1_idx` (`red_idred` ASC),
  INDEX `fk_audi_equipo_disco1_idx` (`disco_iddisco` ASC),
  CONSTRAINT `fk_audi_equipo_audioria`
    FOREIGN KEY (`idauditoria`)
    REFERENCES `mydb`.`audioria` (`idaudioria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_sistema_operativo1`
    FOREIGN KEY (`sistema_operativo`)
    REFERENCES `mydb`.`sistema_operativo` (`idsistema_operativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_cpu1`
    FOREIGN KEY (`cpu`)
    REFERENCES `mydb`.`cpu` (`idcpu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_red1`
    FOREIGN KEY (`red_idred`)
    REFERENCES `mydb`.`red` (`idred`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_disco1`
    FOREIGN KEY (`disco_iddisco`)
    REFERENCES `mydb`.`disco` (`iddisco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
