-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 14:33:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auditoria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `auditoria` ;

-- -----------------------------------------------------
-- Schema auditoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auditoria` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema auditoria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `auditoria` ;

-- -----------------------------------------------------
-- Schema auditoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auditoria` DEFAULT CHARACTER SET utf8 ;
USE `auditoria` ;
USE `auditoria` ;

-- -----------------------------------------------------
-- Table `auditoria`.`auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria`.`auditoria` ;

CREATE TABLE IF NOT EXISTS `auditoria`.`auditoria` (
  `idaudioria` INT(11) NOT NULL AUTO_INCREMENT,
  `audi_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `audi_fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idaudioria`),
  UNIQUE INDEX `idaudioria_UNIQUE` (`idaudioria` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auditoria`.`cpu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria`.`cpu` ;

CREATE TABLE IF NOT EXISTS `auditoria`.`cpu` (
  `idcpu` INT(11) NOT NULL AUTO_INCREMENT,
  `vendedor` VARCHAR(100) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `mhz` VARCHAR(100) NULL DEFAULT NULL,
  `tam_cache` VARCHAR(100) NULL DEFAULT NULL,
  `cpufisica` VARCHAR(100) NULL DEFAULT NULL,
  `nucleoscpu` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idcpu`),
  UNIQUE INDEX `idcpu_UNIQUE` (`idcpu` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auditoria`.`disco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria`.`disco` ;

CREATE TABLE IF NOT EXISTS `auditoria`.`disco` (
  `iddisco` INT(11) NOT NULL AUTO_INCREMENT,
  `espaciototal` VARCHAR(45) NULL DEFAULT NULL,
  `espaciodisponible` VARCHAR(45) NULL DEFAULT NULL,
  `espaciousado` VARCHAR(45) NULL DEFAULT NULL,
  `unidades` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iddisco`),
  UNIQUE INDEX `iddisco_UNIQUE` (`iddisco` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auditoria`.`red`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria`.`red` ;

CREATE TABLE IF NOT EXISTS `auditoria`.`red` (
  `idred` INT(11) NOT NULL AUTO_INCREMENT,
  `ip_primaria` VARCHAR(45) NULL DEFAULT NULL,
  `mac_primaria` VARCHAR(100) NULL DEFAULT NULL,
  `host` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idred`),
  UNIQUE INDEX `idred_UNIQUE` (`idred` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auditoria`.`sistema_operativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria`.`sistema_operativo` ;

CREATE TABLE IF NOT EXISTS `auditoria`.`sistema_operativo` (
  `idsistema_operativo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  `arquitectura` VARCHAR(45) NULL DEFAULT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `directorio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsistema_operativo`),
  UNIQUE INDEX `idsistema_operativo_UNIQUE` (`idsistema_operativo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auditoria`.`audi_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditoria`.`audi_equipo` ;

CREATE TABLE IF NOT EXISTS `auditoria`.`audi_equipo` (
  `idaudi_equipo` INT(11) NOT NULL AUTO_INCREMENT,
  `idauditoria` INT(11) NOT NULL,
  `sistema_operativo` INT(11) NOT NULL,
  `cpu` INT(11) NOT NULL,
  `red_idred` INT(11) NOT NULL,
  `disco_iddisco` INT(11) NOT NULL,
  PRIMARY KEY (`idaudi_equipo`),
  UNIQUE INDEX `idaudi_equipo_UNIQUE` (`idaudi_equipo` ASC),
  INDEX `fk_audi_equipo_audioria_idx` (`idauditoria` ASC),
  INDEX `fk_audi_equipo_sistema_operativo1_idx` (`sistema_operativo` ASC),
  INDEX `fk_audi_equipo_cpu1_idx` (`cpu` ASC),
  INDEX `fk_audi_equipo_red1_idx` (`red_idred` ASC),
  INDEX `fk_audi_equipo_disco1_idx` (`disco_iddisco` ASC),
  CONSTRAINT `fk_audi_equipo_audioria`
    FOREIGN KEY (`idauditoria`)
    REFERENCES `auditoria`.`auditoria` (`idaudioria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_cpu1`
    FOREIGN KEY (`cpu`)
    REFERENCES `auditoria`.`cpu` (`idcpu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_disco1`
    FOREIGN KEY (`disco_iddisco`)
    REFERENCES `auditoria`.`disco` (`iddisco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_red1`
    FOREIGN KEY (`red_idred`)
    REFERENCES `auditoria`.`red` (`idred`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audi_equipo_sistema_operativo1`
    FOREIGN KEY (`sistema_operativo`)
    REFERENCES `auditoria`.`sistema_operativo` (`idsistema_operativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
